apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ordermonitor-api
spec:
  tls:
    - hosts:
        - ordermonitor-api.staging.printerpix.com
      secretName: ordermonitor-api-staging-tls
  rules:
    - host: ordermonitor-api.staging.printerpix.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ordermonitor-api
                port:
                  number: 8080
          - path: /health
            pathType: Exact
            backend:
              service:
                name: ordermonitor-api
                port:
                  number: 8080
          - path: /swagger(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ordermonitor-api
                port:
                  number: 8080
