apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ordermonitor-staging

namePrefix: staging-

bases:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
  - path: ingress-patch.yaml
  - path: configmap-patch.yaml
